@baseURL = http://localhost:3000/api/v1
@postURL = {{baseURL}}/post

GET {{postURL}}
###

GET {{postURL}}/2
###

POST {{postURL}}
Content-Type: application/json

{
    "name": "thien",
}

###

DELETE {{postURL}}/2