@baseURL = http://localhost:3000/api/v1
@userURL = {{baseURL}}/user

GET {{userURL}}
###

GET {{userURL}}/2
###

POST {{userURL}}
Content-Type: application/json

{
    "name": "thien",
}

###

DELETE {{userURL}}/2